#!/usr/bin/env bash
# p3ta-tricks offline launcher — generated by install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_PY="$SCRIPT_DIR/.venv/bin/python3"
TOOLS_DIR="${TOOLS_DIR:-$(dirname "$SCRIPT_DIR")/p3ta-tricks-offline/tools}"
PORT="${PORT:-5001}"
HOST="${HOST:-127.0.0.1}"

# Validate venv
if [ ! -f "$VENV_PY" ]; then
  echo "[!] Virtualenv not found. Run: ./install.sh"
  exit 1
fi

export OFFLINE_MODE=1
export TOOLS_DIR="$TOOLS_DIR"

echo ""
echo "  ┌─────────────────────────────────────────────┐"
echo "  │   p3ta-tricks  —  OFFLINE MODE              │"
echo "  │   http://${HOST}:${PORT}                     │"
echo "  │   TOOLS_DIR: $TOOLS_DIR"
echo "  └─────────────────────────────────────────────┘"
echo ""

cd "$SCRIPT_DIR"

# Use gunicorn if available for stability, fall back to Flask dev server
if [ -f "$SCRIPT_DIR/.venv/bin/gunicorn" ]; then
  exec "$SCRIPT_DIR/.venv/bin/gunicorn"     --bind "${HOST}:${PORT}"     --workers 2     --timeout 60     --access-logfile -     app:app
else
  exec "$VENV_PY" app.py
fi
