#!/usr/bin/env bash
# p3ta-tricks offline launcher — generated by install.sh
#
# Usage:
#   ./start-offline.sh              start in background (default)
#   ./start-offline.sh stop         stop the running instance
#   ./start-offline.sh restart      stop + start
#   ./start-offline.sh status       show pid + URL if running
#   ./start-offline.sh -f           run in foreground (for debug)
#
# Env overrides:
#   PORT=8080 HOST=127.0.0.1 ./start-offline.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_PY="$SCRIPT_DIR/.venv/bin/python3"
GUNICORN="$SCRIPT_DIR/.venv/bin/gunicorn"
TOOLS_DIR="${TOOLS_DIR:-$(dirname "$SCRIPT_DIR")/p3ta-tricks-offline/tools}"
PORT="${PORT:-1339}"
HOST="${HOST:-0.0.0.0}"
PID_FILE="$SCRIPT_DIR/.gunicorn.pid"
LOG_FILE="$SCRIPT_DIR/p3ta-tricks.log"

if [ ! -f "$VENV_PY" ]; then
  echo "[!] Virtualenv not found. Run: ./install.sh"
  exit 1
fi

stop_server() {
  local stopped=0
  if [ -f "$PID_FILE" ]; then
    local PID
    PID=$(cat "$PID_FILE" 2>/dev/null || true)
    if [ -n "${PID:-}" ] && kill -0 "$PID" 2>/dev/null; then
      kill "$PID" 2>/dev/null || true
      sleep 1
      kill -0 "$PID" 2>/dev/null && kill -9 "$PID" 2>/dev/null || true
      stopped=1
    fi
    rm -f "$PID_FILE"
  fi
  # belt-and-suspenders: kill any gunicorn for this app on this port
  pkill -f "gunicorn.*${HOST}:${PORT}.*app:app" 2>/dev/null && stopped=1 || true
  return 0
}

print_status() {
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null; then
    echo "[+] running — pid $(cat "$PID_FILE"), http://${HOST}:${PORT}, log: $LOG_FILE"
  else
    echo "[!] not running"
    return 1
  fi
}

case "${1:-start}" in
  stop)
    stop_server
    echo "[+] stopped"
    exit 0
    ;;
  status)
    print_status
    exit $?
    ;;
  restart)
    stop_server
    ;;
  -f|--foreground|foreground)
    export OFFLINE_MODE=1
    export TOOLS_DIR="$TOOLS_DIR"
    cd "$SCRIPT_DIR"
    echo "[*] p3ta-tricks (foreground) — http://${HOST}:${PORT}"
    exec "$GUNICORN" --bind "${HOST}:${PORT}" --workers 2 --timeout 60 --access-logfile - app:app
    ;;
  start|"")
    ;;
  *)
    echo "usage: $0 [start|stop|restart|status|-f]"
    exit 1
    ;;
esac

# Don't double-start
stop_server

export OFFLINE_MODE=1
export TOOLS_DIR="$TOOLS_DIR"
cd "$SCRIPT_DIR"

# gunicorn --daemon forks to background, writes pidfile, redirects logs to files
"$GUNICORN" \
  --bind "${HOST}:${PORT}" \
  --workers 2 \
  --timeout 60 \
  --pid "$PID_FILE" \
  --daemon \
  --access-logfile "$LOG_FILE" \
  --error-logfile "$LOG_FILE" \
  app:app

# wait a moment for gunicorn to bind
for _ in 1 2 3 4 5; do
  if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null; then
    break
  fi
  sleep 1
done

if [ -f "$PID_FILE" ] && kill -0 "$(cat "$PID_FILE" 2>/dev/null)" 2>/dev/null; then
  PID=$(cat "$PID_FILE")
  echo ""
  echo "  ┌─────────────────────────────────────────────────────────────┐"
  echo "  │   p3ta-tricks — running in background                       │"
  echo "  │   URL:   http://${HOST}:${PORT}"
  echo "  │   PID:   $PID"
  echo "  │   Log:   $LOG_FILE"
  echo "  │   Stop:  ./start-offline.sh stop"
  echo "  └─────────────────────────────────────────────────────────────┘"
  echo ""
else
  echo "[!] gunicorn failed to start — check $LOG_FILE"
  tail -20 "$LOG_FILE" 2>/dev/null
  exit 1
fi
